spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 63fba97a41e0d004e10e8dbbcb9a547819280efb00a54c732aca36a8a58258e4fcc539ffc5159a7f0a7be78b86efe001c12ba6af6debeb0a89e8ce7e82e75455

  access:
    expiration: 90
    # header: Authorization

  refresh:
    expiration: 900
    #header: Authorization-refresh