spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: woojin
    password: 1359ki
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect