POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
content-Type: application/json
x-goog-api-key: AIzaSyBpX38E9lu0OwI5z6NahIQBDi0DFVSeog0

{
  "contents": [{
    "parts":[{
      "text": "서울 맛집을 추천해줘"
    }]
  }]
}

###
POST http://localhost:8080/ai/chat
Content-Type: application/json

