### 유저 회원가입
POST localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "userName": "master2",
  "password": "password2",
  "nickName": "mst2",
  "email": "master2@example.com",
  "phoneNumber": "010-1234-0022",
  "address": "주소22"
}

### 유저 로그인(매니저)
POST localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email" : "manager2@example.com",
  "password" : "password2"
}

> {%
    client.log(response.headers.valueOf("Authorization"));
    client.log(response.headers.valueOf("Authorization-refresh"));
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.global.set("Authorization-refresh", response.headers.valueOf("Authorization-refresh"));
%}

### 유저 로그인(오너)
POST localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email" : "owner2@example.com",
  "password" : "password2"
}

> {%
    client.log(response.headers.valueOf("Authorization"));
    client.log(response.headers.valueOf("Authorization-refresh"));
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.global.set("Authorization-refresh", response.headers.valueOf("Authorization-refresh"));
%}